apiVersion: v1
kind: Service
metadata:
  name: fitness-service
spec:
  type: NodePort
  selector:
    app: fitness
  ports:
    - port: 80           # Service port (inside cluster)
      targetPort: 80     # Container port (inside pod)
      nodePort: 30081    # External port (Node/Minikube)
